### ISSUE TITLE
[FEATURE] Finding compatible variants in frontends

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#192]
### Description

The original issue can be found in slack [here](https://shopwarecommunity.slack.com/archives/C050L6NCMGQ/p1683203566261369?thread_ts=1683186819.417099&cid=C050L6NCMGQ) and was reported by [Stephan Lukachyna](https://shopwarecommunity.slack.com/team/U02R2RMLGBW).

---

I have 5 variants and I make 5 fetches. First fetch have filter like:
```
[
    {
        "type": "equals",
        "field": "parentId",
        "value": "2343d14b25804a9ebb95a89e76ac1592"
    },
    {
        "type": "multi",
        "operator": "and",
        "queries": [
            {
                "type": "equals",
                "field": "optionIds",
                "value": "b19c002cc88240d89865224c7e006a79"
            }
        ]
    }
]
```
I try to find all variants which compatible with the first optionIds.
The second fetch, I try to find all compatible variants for FIRST AND SECOND OPTION
```
  {
      "type": "equals",
      "field": "parentId",
      "value": "2343d14b25804a9ebb95a89e76ac1592"
  },
  {
      "type": "multi",
      "operator": "and",
      "queries": [
          {
              "type": "equals",
              "field": "optionIds",
              "value": "b19c002cc88240d89865224c7e006a79"
          },
          {
              "type": "equals",
              "field": "optionIds",
              "value": "dc4a62f525e343b8846071dfbeeb90af"
          }
      ]
  }
```
And so on. Not sure maybe my fail but I didn’t find another approach (bearbeitet) 

[@Björn](https://shopwarecommunity.slack.com/team/U015WB0KL2Y) Actually yesterday my back guy found in repository the field which call "combinable" Looks like it helps me reduce fetches but again we need create custom plugin with custom route which will provide for us this field cuz  in store-api it missing

Here is our solution (PHP) if u interesting:
```
public function getOptions(Criteria $criteria, SalesChannelContext $context) : array
    {
        $variants = $this->product->search($criteria, $context);
        $variant = $variants->first();

        $result = [];
        $result['variantId'] = $variant->getProductNumber();

        $properties = $this->loader->load($variant, $context)->getElements();
        foreach ($properties as $property) {
            foreach ($property->getOptions() as $option) {
                $result['options'][$property->getId()][] = [
                    "id"            => $option->getId(),
                    "name"          => $option->getName(),
                    "combinable"    => $option->getCombinable(),
                    "position"      => $option->getPosition(),
                    "extra_price"   => $option->getConfiguratorSetting()->getPrice()[0]['gross']
                ];
            }
            usort($result['options'][$property->getId()], function ($a, $b) {
                return $a['position'] <=> $b['position'];
            });
        }
        return $result;
    }
```

### Use Case

Finding compatible variants in frontends (to show possible selections already on category page).

_For me (Björn) this sounds a bit like the same issue [Tanja Bayer](https://shopwarecommunity.slack.com/team/U03M66NEU93) reported in pwa channel, see this [thread](https://shopwarecommunity.slack.com/archives/C02TZE6UCJZ/p1683102488960879) in community slack._

**Comment by BrocksiNet** [comment]
Hey @mkucmus can you tell why this is blocked, maybe just a short hint.

**Comment by mkucmus** [comment]
Due to the fact that the problem is addressed to product listing context, and requires to have additional fields (like `combinable` - from an example in this issue), any solution we can provide as long as it's possible, it won't be sufficient, and it should be addressed to the backend/API side. I couldn't find a way to expose one magic method to solve the problem, and also I think having additional few requests on listing page is not a perfect solution :(

**Comment by BrocksiNet** [comment]
There is now a [task](https://shopware.atlassian.net/browse/NEXT-28229) created for this issue in Jira for the core team.

**Comment by BrocksiNet** [comment]
This can be solved without changes needed to the core.
This is already solved in the react vercel commerce template, see [here](https://github.com/shopwareLabs/vercel-commerce/blob/main/lib/shopware/criteria.ts#L55) and [here](https://github.com/shopwareLabs/vercel-commerce/blob/main/components/product/variant-selector.tsx).
We just need to transfer this into a composable and an example.

**Comment by BrocksiNet** [comment]
Wrote a [blog post](https://www.brocksi.net/blog/variants-selection-multi-page-or-single-page/) to explain everything you need to know.

**Comment by eliasws** [comment]
@BrocksiNet
I came across this issue as we’re facing the same challenge with complex variants. I was also wondering if there’s a way to expose the combinable field. Is there any update on the related Jira issue?

By the way, I really enjoyed the blog post! However, in my opinion, this issue is still unresolved for the Vue project:

![Image](https://github.com/user-attachments/assets/ea56b795-e6f9-43a6-9009-e6476ae6a4a4)

In the multi-page version, users can’t easily determine which variant combinations are valid, nor is there a way to highlight them—unless using the single-page version. This leads to frequent encounters with the “Provided variant is empty” warning when working with complex variants.

Would appreciate any insights on this! 🚀

**Comment by BrocksiNet** [comment]
@eliasws, you are right. It is not solved in the vue-demo store template. But it is solved in the react template, which means it is also possible in vue, but you need to transfer it. That's the reason why I mentioned both solutions. The internal task is closed because it is already possible and does not need any core changes to work. It is just how you transform and use the data in the frontend.

@mkucmus @patzick @mdanilowicz, maybe we should consider this when building the new templates.

**Comment by eliasws** [comment]
@BrocksiNet
I checked out the React template, and the issue seems to be that it doesn’t use a CMS Page. Instead, it relies on retrieving the parent via the `store-api/product POST request`. However, even when the CMS Page association is set, the response doesn’t include CMS the CMS Page—unlike the `store-api/product/{productId} Product Detail` request (see ProductDetailRoute.php:105).

Key Issues (At Least for Us):
	•	If you rely on the children’s availability (React example), you have to use product search, but this means CMS content isn’t available without making an additional request.
	•	If you want to use CMS (Vue example), you need to use the Detail route, which returns the “best child” but not sibling variants, making it impossible to check children’s availability—again, without an extra request.

Our Solution:

We decided to stick with the Vue approach and made the following adjustments:
	1.	Added a decorator to expose combinable as a custom field.
	2.	Modified the composable logic to reset filters when a user selects a non-combinable option.
